-- Lab 3: partition project adoptions by month (RANGE on created_at)
-- Strategy: new parent table + migrate + swap (for lab/demo)

BEGIN;

-- Save existing if needed
DROP TABLE IF EXISTS adoptions_old CASCADE;
DROP TABLE IF EXISTS adoptions_partitioned CASCADE;

CREATE TABLE adoptions_partitioned (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    animal_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    adoption_date DATE NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Pending',
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    PRIMARY KEY (id, created_at),
    CONSTRAINT fk_adoptions_p_animal FOREIGN KEY (animal_id) REFERENCES animals(id) ON DELETE RESTRICT,
    CONSTRAINT fk_adoptions_p_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT
) PARTITION BY RANGE (created_at);

-- Monthly partitions: past months covering data + current + horizon
CREATE TABLE adoptions_2024_01 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2024-01-01') TO ('2024-02-01');
CREATE TABLE adoptions_2024_02 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2024-02-01') TO ('2024-03-01');
CREATE TABLE adoptions_2024_03 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2024-03-01') TO ('2024-04-01');
CREATE TABLE adoptions_2024_04 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2024-04-01') TO ('2024-05-01');
CREATE TABLE adoptions_2024_05 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2024-05-01') TO ('2024-06-01');
CREATE TABLE adoptions_2024_06 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2024-06-01') TO ('2024-07-01');
CREATE TABLE adoptions_2024_07 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2024-07-01') TO ('2024-08-01');
CREATE TABLE adoptions_2024_08 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2024-08-01') TO ('2024-09-01');
CREATE TABLE adoptions_2024_09 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2024-09-01') TO ('2024-10-01');
CREATE TABLE adoptions_2024_10 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2024-10-01') TO ('2024-11-01');
CREATE TABLE adoptions_2024_11 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2024-11-01') TO ('2024-12-01');
CREATE TABLE adoptions_2024_12 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2024-12-01') TO ('2025-01-01');
CREATE TABLE adoptions_2025_01 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2025-01-01') TO ('2025-02-01');
CREATE TABLE adoptions_2025_02 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2025-02-01') TO ('2025-03-01');
CREATE TABLE adoptions_2025_03 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2025-03-01') TO ('2025-04-01');
CREATE TABLE adoptions_2025_04 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2025-04-01') TO ('2025-05-01');
CREATE TABLE adoptions_2025_05 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2025-05-01') TO ('2025-06-01');
CREATE TABLE adoptions_2025_06 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2025-06-01') TO ('2025-07-01');
CREATE TABLE adoptions_2025_07 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2025-07-01') TO ('2025-08-01');
CREATE TABLE adoptions_2025_08 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2025-08-01') TO ('2025-09-01');
CREATE TABLE adoptions_2025_09 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2025-09-01') TO ('2025-10-01');
CREATE TABLE adoptions_2025_10 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2025-10-01') TO ('2025-11-01');
CREATE TABLE adoptions_2025_11 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2025-11-01') TO ('2025-12-01');
CREATE TABLE adoptions_2025_12 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2025-12-01') TO ('2026-01-01');
CREATE TABLE adoptions_2026_01 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');
CREATE TABLE adoptions_2026_02 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');
CREATE TABLE adoptions_2026_03 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');
CREATE TABLE adoptions_2026_04 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2026-04-01') TO ('2026-05-01');
CREATE TABLE adoptions_2026_05 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
CREATE TABLE adoptions_2026_06 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');
CREATE TABLE adoptions_2026_07 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE adoptions_2026_08 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE adoptions_2026_09 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE adoptions_2026_10 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
CREATE TABLE adoptions_2026_11 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2026-11-01') TO ('2026-12-01');
CREATE TABLE adoptions_2026_12 PARTITION OF adoptions_partitioned
FOR VALUES FROM ('2026-12-01') TO ('2027-01-01');
-- default catch-all for out-of-range
CREATE TABLE adoptions_default PARTITION OF adoptions_partitioned DEFAULT;

CREATE INDEX idx_adoptions_p_user_status_created ON adoptions_partitioned (user_id, status, created_at DESC);
CREATE INDEX idx_adoptions_p_animal_id ON adoptions_partitioned (animal_id);
CREATE INDEX idx_adoptions_p_status ON adoptions_partitioned (status);

INSERT INTO adoptions_partitioned (id, animal_id, user_id, adoption_date, status, notes, created_at, updated_at)
SELECT id, animal_id, user_id, adoption_date, status, notes, created_at, updated_at FROM adoptions;

-- Swap
ALTER TABLE adoptions RENAME TO adoptions_old;
ALTER TABLE adoptions_partitioned RENAME TO adoptions;

-- Identity sequence sync
SELECT setval(pg_get_serial_sequence('adoptions', 'id'), (SELECT COALESCE(MAX(id), 1) FROM adoptions));

COMMIT;

ANALYZE adoptions;

-- Demonstrate pruning
EXPLAIN (ANALYZE, BUFFERS)
SELECT * FROM adoptions
WHERE created_at >= DATE '2026-03-01' AND created_at < DATE '2026-04-01'
LIMIT 50;

EXPLAIN (ANALYZE, BUFFERS)
SELECT * FROM adoptions WHERE user_id = 2 ORDER BY created_at DESC LIMIT 50;

SELECT tableoid::regclass AS partition, COUNT(*) FROM adoptions GROUP BY 1 ORDER BY 1;
